#!/usr/bin/perl

use strict;
use warnings;

my $homeDir = $ENV{"HOME"};
my $ideaDir = $ARGV[0];
my $backupDir = $ARGV[1];
my @subDirs = ("Application Support", "Caches", "Logs", "Preferences");

print "Backing up to $backupDir\n";
for my $subDir (@subDirs) {
  runCommand("mkdir -p \"$backupDir/$subDir\"");
}

for my $subDir (@subDirs) {
  runCommand("cp -a \"$homeDir/Library/$subDir/$ideaDir\" \"$backupDir/$subDir/$ideaDir\"");
}

sub runCommand {

  my $cmd = shift;

  print STDERR "Executing $cmd...";
  system($cmd);
  print STDERR " done.\n";

  if ($? != 0) {
    print STDERR "Command \"$cmd\" failed, return value was $?\n";
    exit 1;
  } else {
    return 1;
  }

}
